<?php
session_start();
require 'connection.php';
require('vendor/autoload.php');
use Razorpay\Api\Api;

// Check login
if (!isset($_SESSION['user_id'])) {
    echo "user_not_logged_in";
    exit;
}

$user_id = $_SESSION['user_id'];
$course_id = intval($_POST['course_id'] ?? 0);
$amount = floatval($_POST['amount'] ?? 0);
$razorpay_payment_id = $_POST['razorpay_payment_id'] ?? '';
$razorpay_order_id = $_POST['razorpay_order_id'] ?? '';
$razorpay_signature = $_POST['razorpay_signature'] ?? '';

// Validate inputs
if ($course_id <= 0 || $amount <= 0 || empty($razorpay_payment_id)) {
    echo "invalid_input";
    exit;
}

// Initialize Razorpay for verification
$api = new Api(RAZORPAY_KEY_ID, RAZORPAY_KEY_SECRET);

try {
    // Verify payment signature
    $attributes = array(
        'razorpay_order_id' => $razorpay_order_id,
        'razorpay_payment_id' => $razorpay_payment_id,
        'razorpay_signature' => $razorpay_signature
    );

    $api->utility->verifyPaymentSignature($attributes);

    // Payment verification successful
    // Now save to database

    // First, fetch the tutor_id for this course, as it's required for both tables
    $tutor_query = $conn->prepare("SELECT tutor_id FROM course_tbl WHERE course_id = ? LIMIT 1");
    $tutor_query->bind_param("i", $course_id);
    $tutor_query->execute();
    $tutor_result = $tutor_query->get_result();
    $tutor_data = $tutor_result->fetch_assoc();
    $tutor_id = $tutor_data['tutor_id'] ?? 0;

    // ============================
    // 1️⃣ Insert into user_payment_tbl
    // ============================
    $status_success = 1; // Assuming 1 is success based on typical tinyint flags
    $query = "
        INSERT INTO user_payment_tbl (user_id, tutor_id, course_id, amount, razorpay_id, payment_status, payment_date)
        VALUES (?, ?, ?, ?, ?, ?, NOW())
    ";

    $stmt = $conn->prepare($query);
    $stmt->bind_param("iiidsi", $user_id, $tutor_id, $course_id, $amount, $razorpay_payment_id, $status_success);

    if (!$stmt->execute()) {
        echo "payment_failed: " . $conn->error;
        exit;
    }

    // Get AUTO_INCREMENT user_payment_id generated by MySQL
    $user_payment_id = $stmt->insert_id;

    // ============================
    // 2️⃣ Insert into enrollments_tbl ONLY if not enrolled
    // ============================
    $check = $conn->prepare("
        SELECT 1 FROM enrollments_tbl 
        WHERE user_id = ? AND course_id = ? LIMIT 1
    ");
    $check->bind_param("ii", $user_id, $course_id);
    $check->execute();
    $result = $check->get_result();

    if ($result->num_rows == 0) {
        $enroll_status = 'active';
        $progress = 0;
        $enrollQuery = "
            INSERT INTO enrollments_tbl (user_id, tutor_id, course_id, user_payment_id, amount, enrollment_status, enrolled_at, progress)
            VALUES (?, ?, ?, ?, ?, ?, NOW(), ?)
        ";

        $insertEnroll = $conn->prepare($enrollQuery);
        $insertEnroll->bind_param("iiiidsi", $user_id, $tutor_id, $course_id, $user_payment_id, $amount, $enroll_status, $progress);

        if (!$insertEnroll->execute()) {
            echo "enrollment_failed: " . $conn->error;
            exit;
        }
    }

    echo "success";

} catch (Exception $e) {
    // Payment verification failed
    error_log("Razorpay verification failed: " . $e->getMessage());
    echo "verification_failed: " . $e->getMessage();
}
?>